.TH loliwm 1 "October 25" loliwm
.SH NAME
loliwm \- Dynamic wayland compositor.
.SH SYNOPSIS
\fBloliwm\fP [options]
.SH DESCRIPTION
\fBloliwm\fP is a dynamic window manager and compositor for Wayland built using
the wlc library.
.SH OPTIONS
.IP "\fB\-\-prefix\fR \fImodifier\fR
Defines a modifier (or modifiers) to be used with the default keybindings.
Multiple modifiers may be set such as \%\fB--prefix ctrl,atl\fR which would
represent the keybindings as \%\fIctrl-alt-<key>\fR. Possible choices included
\fIshift\fR,
\fIcaps\fR,
\fIctrl\fR,
\fIalt\fR,
\fImod2\fR,
\fImod3\fR,
\fIlogo\fR and
\fImod5\fR. (Default: \fIalt\fR)

N.B. \fIlogo\fR is typically the "Windows" or Super key.
.IP "\fB\-\-log\fR [\fIFILE\fR]"
File in which the logging output is captured.
.IP \fB\-\-shm\fR
Force EGL clients to fallback on shm.
.SH KEYBINDINGS
N.B. These are a tentative set of keybindings created specifically to provide
basic usage until more flexible mechanisms are added.
.IP \fBmod\-return\fR
Opens a new terminal emulator client.
.IP \fBmod-p\fR
Opens \fBbemenu-run\fR (similar to \fBdmenu_run\fR) for starting applications.
.IP \fBmod\-l\fR
Rotates focus through clients.
.IP \fBmod\-k\fR
Rotates focus through available outputs.
.IP \fBmod\-[1..n]\fR
Selects the \fInth\fP workspace, currently limited to ten.
.IP \fBmod\-F1..F10\fR
Moves the focused client to the corresponding workspace.
.IP "\fBmod-z, x, c\fR"
Moves focused client to outputs 1, 2 and 3 respectively.
.IP \fBmod-h\fR
Cycles the focused client.
.IP \fBmod-q\fR
Closes the focused client.
.IP "\fBmod-i, o\fR"
Shifts the cut of the nmaster layout to shrink or expand the view.
.IP \fBmod-print\fR
Takes a screenshot in PPM (Portable Pixmap) format and stores it in the directory
loliwm was started from.
.IP \fBmod-escape\fR
Quits \fBloliwm\fR.
.SH ENVIRONMENT
.IP \fBTERMINAL\fR
Currently \fBloliwm\fR will honor this environment variable when starting a new
terminal emulator. If this is not set it will fall back on \fBweston-terminal\fR.
.IP \fBXKB_DEFAULT_LAYOUT\fR
This corresponds to the layout you might use in X11 such as \fBgb\fR.  Use this
if you want to select a non-us keyboard layout.
.IP \fBXKB_DEFAULT_OPTIONS\fR
Sets the keyboard options. The syntax is the same (comma-separated values) as
within an \fIxorg.conf\fR or when used via \%\fBsetxkbmap -option\fR.
For example \%\fBcompose:ralt,ctrl:nocaps\fR would set \fIralt\fR to the compose
key and cause the \fICaps Lock\fR key to mimic \fIctrl\fR.
.IP \fBXKB_DEFAULT_VARIANT\fR
.IP \fBXKB_DEFAULT_RULES\fR
.IP \fBXKB_DEFAULT_MODEL\fR
.SH AUTHORS
.IP "Jari Vetoniemi <http://cloudef.pw/>"
.SH SEE ALSO
\fBxkbcommon\fR,
\fBwayland\fR,
\fBweston\fR
